url: https://flrproject.org

# Site settings
title: FLR
email: flr-team@flrproject.org
description: "The homepage of the FLR Project for open source quantitative fisheries science in R"

# Team names, titles and social links
people:
- name: Kay Garland
  pic: 1
  position: Lead Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Larry Parker
  pic: 2
  position: Lead Marketer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/flr
  - title: r-universe
    url: https://flr.r-universe.dev
  - title: twitter
    url: https://twitter.com/flrproject

# Postal address (add as many lines as necessary)
address:
  - line: WUR IJmuiden
  - line: The Netherlands

# Build settings
markdown: kramdown
permalink: pretty
highlighter: rouge
